### ISSUE TITLE
[tracking] Minor issues

### ISSUE THREAD

**Issue by bui** [bui/taiko-web#18]
- [x] Notes should have shadows (AC0)
- [x] `score-*` assets should be modified to make the text bigger (AC0)
- [ ] Combo/score update animations
- [ ] Use ド and カ underneath notes when appropriate
- [x] Extend 連打ーっ!! to length of drumroll
- [x] On easy, play renda voice file when a drumroll starts
- [x] Display difficulty and use proper crown assets in results screen (AC0)
